name: Build

inputs:
  debug:
    description: Sets "NODE_ENV" to "debug".
    required: false
    default: ''

runs:
  using: composite

  steps:
    - uses: actions/checkout@v4.1.0

    - name: TODO
      run: 'echo Debug mode is $NODE_ENV jau.'
      shell: bash

    # Runs a set of commands using the runners shell

    #- name: Install yarn
    #  run: npm install --global yarn
    #  shell: bash

    - name: Disable node version check
      run: yarn config set ignore-engines true
      shell: bash

    - name: Install packages marked as dependencies
      env:
        NODE_ENV: ${{ inputs.debug }}
      run: yarn
      shell: bash
