name: Build

inputs:
  debug:
    description: Sets "NODE_ENV" to "debug".
    required: false
    default: false
  fetch-depth:
    description: Number of commits to fetch. 0 indicates all history for all branches and tags.
    default: 1
  fetch-tags:
    description: Whether to fetch tags, even if fetch-depth > 0.
    default: false

runs:
  using: composite

  steps:
    - name: Checkout repository.
      uses: actions/checkout@v4
      with:
        fetch-depth: ${{ inputs.fetch-depth || 1 }}
        fetch-tags: ${{ inputs.fetch-tags || true }}

    - name: Enable corepack to utilize latest or specified package manager.
      run: corepack enable
      shell: bash

    - name: Install specified package manager.
      run: corepack install
      shell: bash

    - name: Install packages marked as dependencies
      env:
        NODE_ENV: ${{ contains(inputs.debug, 'true') && 'debug' }}
        YARN_ENABLE_IMMUTABLE_INSTALLS: false
      run: yarn install
      shell: bash
