name: Build

inputs:
  debug:
    description: Sets "NODE_ENV" to "debug".
    required: false
    default: false

runs:
  using: composite

  steps:
    - uses: actions/checkout@v4.2.2

    - name: Enable corepack to utilize latest or specified package manager.
      run: corepack enable
      shell: bash

    - name: Install specified package manager.
      run: corepack install
      shell: bash

    - name: Install packages marked as dependencies
      env:
        NODE_ENV: ${{ contains(inputs.debug, 'true') && 'debug' }}
        YARN_ENABLE_IMMUTABLE_INSTALLS: false
      run: yarn install
      shell: bash
